# Newly added
fit:
  model:
    d_model: 256 # 256
    growth_rate: 24
    num_layers: 16
    nhead: 8
    num_decoder_layers: 3 # 3
    dim_feedforward: 1024 # 1024
    dropout: 0.3
    beam_size: 10
    max_len: 200
    alpha: 1.0
    learning_rate: 1.0
    patience: 20
  trainer:
    callbacks:
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: epoch
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          save_top_k: 1
          monitor: val_ExpRate
          mode: max
          filename: '{epoch}-{step}-{val_ExpRate:.4f}'
    max_epochs: 300
    accelerator: cuda
    devices: 1
    check_val_every_n_epoch: 2
  # Resume from checkpoint
  ckpt_path: 'lightning_logs\Intial_attempt\checkpoints\epoch=17-step=27018-val_ExpRate=0.1939.ckpt'