# Newly added
fit:
  model:
    d_model: 256
    growth_rate: 24
    num_layers: 16
    nhead: 8
    num_decoder_layers: 3
    dim_feedforward: 1024
    dropout: 0.3
    beam_size: 10
    max_len: 200
    alpha: 1.0
    learning_rate: 1.0
    patience: 20